---
- include: "{{ansible_distribution}}.yml"
  tags: redis

- name: Provide redis configuration file
  tags: redis
  template: 
    src: redis.conf
    dest: /etc/redis/redis.conf
    mode: "0644"
  notify:
    - Restart redis service

