---
## Nginx is installed as dependencies of hublin role
- hosts: tag_hublin-master
  become: True
  vars_files:
    - config.yml
  roles:
    - hosts
    - mongodb
    - redis
    - coturn
    - node
    - hublin

- hosts: tag_hublin-slave
  become: True
  vars_files:
    - config.yml
  roles:
    - node
    - coturn
    - hublin

- hosts: tag_hublin-slave-local
  become: True
  connection: local
  vars_files:
    - config.yml
  roles:
    - node
    - coturn
    - hublin
