---
- name: Install Debian packages
  tags: node
  apt: pkg={{item}} state=latest update_cache=yes
  with_items:
    - wget
    - curl
    - make
    - g++
    - gcc
    - libcurl4-openssl-dev
    - libsasl2-2
    - libsasl2-dev
    - libcurl3
    - apt-transport-https
    - lsb-release
    - nodejs

