---

# http://www.grulic.org.ar/~mdione/glob/posts/installing-npm-on-debian-testing/
- name: npm calls it node for some reason
  tags: npm
  become: True
  file:
    state: link
    src: /usr/bin/nodejs
    dest: /usr/local/bin/node

- name: Download npm
  tags: npm
  unarchive:
    src: https://registry.npmjs.org/npm/-/npm-5.3.0.tgz
    dest: /tmp
    remote_src: True

- name: Install npm
  tags: npm
  become: True
  register: npm_install_output
  shell: cd /tmp/package; nodejs bin/npm-cli.js install -gf

- name: NPM Install global packages
  tags: node
  when: nodejs_global_packages is defined
  npm: name={{item}} global=yes
  with_items: "{{ nodejs_global_packages }}"

# Somehow ~/.npm/_cacache/tmp/  gets owned by the remote user and that causes permission denied...
- name: npm cache fix owner
  tags: npm
  become: True
  file:
    state: absent
    path: "{{ '~/.npm/_cacache' | expanduser }}"


